spring:
  application:
    name: OTC_project
  datasource:
    url: jdbc:mysql://118.31.237.118:3306/otc_test
    username: root
    password: "030714"
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8443

mybatis:
  type-aliases-package: com.example.otc_project.entity
  mapper-locations: classpath:mapper/*.xml